apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-controller
    spec:
      containers:
      - name: sample-controller
        image: sample-controller:latest
        args:
        - "-logtostderr=true"
        - "-stderrthreshold=INFO"
